### ISSUE TITLE
Replace if BUILD_UT with ifdef BUILD_UT in generated C++

### ISSUE THREAD

**Issue by bocchino** [nasa/fpp#374]
The build system defines BUILD_UT to 1 when building unit tests; otherwise it leaves BUILD_UT undefined. On some platforms, `#if BUILD_UT` causes an error when BUILD_UT is undefined. See https://github.com/fprime-community/fpp/issues/369#issuecomment-1877779973.

**Comment by jwest115** [comment]
@bocchino I looked for all occurrences of `if BUILD_UT` and only found a few in fpp-to-cpp test (ex: Fw/Buffer/Buffer.cpp) and in the user guide examples. It looks like the CPP codegen includes `ifdef BUILD_UI` [here](https://github.com/nasa/fpp/blob/main/compiler/lib/src/main/scala/codegen/CppWriter/CppWriterUtils.scala#L156), so maybe this was previously addressed?

**Comment by bocchino** [comment]
After review, I think this issue is superseded by the following issue in F Prime: https://github.com/nasa/fprime/issues/2467. I'll close this issue as completed. No further action on this issue is required. Thanks!
