### ISSUE TITLE
Integrate Phase 1 state machines with F Prime

### ISSUE THREAD

**Issue by garthwatney** [nasa/fpp#478]
https://github.com/garthwatney/fprime/tree/sm-test
See FppTest/state-machine
- Review and finalize this branch
- Make a PR to fprime devel

The latest STARS can be found here:  https://github.com/JPLOpenSource/STARS/tree/main

**Comment by bocchino** [comment]
Integration is happening via this PR: https://github.com/nasa/fprime/pull/2829.

**Comment by bocchino** [comment]
The PR is merged! Thanks to @garthwatney and @LeStarch.
